version: '3.8'
services:

    app:
        build:
          dockerfile: Dockerfile-back
        command: 'php app.php start'
        ports:
            - "8000:8000"
        environment:
          - PORT=8000
        volumes:
          - .:/app
