version: '3.8'
services:

    app:
        build:
          dockerfile: Dockerfile
        ports:
            - "8000:8000"
        environment:
          - DB_HOST=db
          - DB_PORT=3306
          - DB_USER=root
          - DB_PASS=root
          - DB_NAME=test
          - DB_CHARSET=utf8
          - ATOL_BASE_URI=https://testonline.atol.ru/possystem/v5/
          - ATOL_GROUP_CODE=v5-online-atol-ru_5179
          - ATOL_LOGIN=v5-online-atol-ru
          - ATOL_PASS=zUr0OxfI
          - ATOL_CALLBACK_URL=
          - REDIS_HOST=redis
          - REDIS_PORT=6379
          - REDIS_PASSWORD=redis_password
        depends_on:
          - db
          - redis
        volumes:
          - .:/app

    db:
      image: mariadb:10.3.27
      volumes:
        - ./docker/db/data:/var/lib/mysql
        - ./docker/db/init:/docker-entrypoint-initdb.d
      environment:
        MYSQL_DATABASE: test
        MYSQL_ROOT_PASSWORD: root
        MYSQL_PASSWORD: root
#        MYSQL_USER: root
      ports:
        - "33060:3306"

    redis:
      image: redis:6.0.20-alpine3.18
      restart: always
      ports:
        - '6379:6379'
      command: redis-server --save 20 1 --loglevel warning --requirepass redis_password
      volumes:
        - ./docker/redis/data:/data
